---
title: "UMD Part 3 - BIOS 611"
author: "Monica E Borges"
date: "11/13/2019"
output: html_document
---

### Introduction to UMD


### Goals of this report
* To describe a big picture of the comings-and-goings-of clients at the UMD shelter
* Observe overall growth in new visitors since 2012
* Incorporate demographics from UMD and Durham to descriptive visuals
* Describe any temporal trends in client arrival and departure
* Investigate how long people stay at UMD, overall and with regard to survey results

#### Who is coming to the UMD shelter, and how have clients grown since 2012?
age histogram: 
* distribution of ages of clients when they first come to UMD shelter
* compared to [durham age demographics in 2017](http://worldpopulationreview.com/us-cities/durham-population/)







Destination after UMD by housing status at Entry
Rental                        Owned         Friends/family, temp    Friends/family, permanent 
 478                            5                         2035                          225 
Hospital/psych/care facility Shelter/project/transitional           Unknown                         Jail 
           203                          111                         1633                           43 






